- id: cmmsg
  name: cmmsg
  description: "A plugin for pre-commit, to check the commit msg before your commit."
  entry: cmmsg
  stages: [commit-msg]
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]